import product from "../public/images/shoe.jpg";

export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambara",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const categories = [
  {
    title: "Art",
    image: product,
    slug: "art",
  },
  {
    title: "Computing",
    image: product,
    slug: "computing",
  },
  {
    title: "Electronics",
    image: product,
    slug: "electronics",
  },
  {
    title: "Phones & Tablets",
    image: product,
    slug: "phones-tablets",
  },
  {
    title: "Mobile Accessories",
    image: product,
    slug: "mobile-accessories",
  },
  {
    title: "Groceries",
    image: product,
    slug: "groceries",
  },
  {
    title: "Food & Beverages",
    image: product,
    slug: "food-beverages",
  },
  {
    title: "Household",
    image: product,
    slug: "household",
  },
  {
    title: "Male Fashion",
    image: product,
    slug: "male-fashion",
  },
  {
    title: "Female Fashion",
    image: product,
    slug: "female-fashion",
  },
  {
    title: "Unisex Fashion",
    image: product,
    slug: "unisex-fashion",
  },
  {
    title: "Shoes & Footwear",
    image: product,
    slug: "shoes-footwear",
  },
  {
    title: "Jewelry",
    image: product,
    slug: "jewelry",
  },
  {
    title: "Kids Corner",
    image: product,
    slug: "kids-corner",
  },
  {
    title: "Sporting Goods",
    image: product,
    slug: "sporting-goods",
  },
  {
    title: "Health & Beauty",
    image: product,
    slug: "health-beauty",
  },
  {
    title: "Services",
    image: product,
    slug: "services",
  },
  {
    title: "Others",
    image: product,
    slug: "others",
  },
];
